/*
 * This file is generated by jOOQ.
 */
package com.treetory.jooq.entity;


import com.treetory.jooq.entity.tables.Sample;
import com.treetory.jooq.entity.tables.records.SampleRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<SampleRecord, Integer> IDENTITY_SAMPLE = Identities0.IDENTITY_SAMPLE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SampleRecord> CONSTRAINT_9 = UniqueKeys0.CONSTRAINT_9;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<SampleRecord, Integer> IDENTITY_SAMPLE = Internal.createIdentity(Sample.SAMPLE, Sample.SAMPLE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<SampleRecord> CONSTRAINT_9 = Internal.createUniqueKey(Sample.SAMPLE, "CONSTRAINT_9", Sample.SAMPLE.ID);
    }
}
