/*
 * This file is generated by jOOQ.
 */
package com.treetory.jooq.entity;


import com.treetory.jooq.entity.tables.Sample;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.SAMPLE</code>.
     */
    public static final Sample SAMPLE = com.treetory.jooq.entity.tables.Sample.SAMPLE;
}
